@startuml
!pragma layout smetana

  actor user

  usecase "Customer" as UC1
  usecase "TicketHandler" as UC2
  usecase "Return" as UC3
  usecase "Payment" as UC4


user --> UC1
UC1 --> UC4
UC4 --> UC2
UC2 --> UC3



@enduml
