@startuml
!pragma layout smetana
class Main{
+ static void main(String[] args)
}



class Customer {
    + Account
    - List<Item> Valuables
}

class Company {
    - int Capacity

}

class TicketHandler {
    + TicketGeneration(Customer);
    + TicketRemoval(Customer):
}

class Admin {
    - Statistic WaitTime
}

class CustomerService {
    assistCustomer();
}

class Payment {
    -Pay(Customer, account)
}

class Organizer {
    -boolean multipleWardrobes
    +hasMulitpleWardrobes
}

class Location {
    - String Venue
}

class ErrorHandler {
}

class FileIO {
    +SaveData(path);
    +RemoveData(path);
}

class Item {


}

class Statistic {
    +customerAmount
    +calculateWaitTime
    +showStatistics
}

Main "1" -- "*" Company : uses >
Customer "1" -- "*" Item : has >

Company "1" -- "*" Customer : serves >
Company "1" -- "*" TicketHandler : uses >
Company "1" -- "1" Admin : manages >
Company "1" -- "1" Organizer : coordinates >
Company "1" -- "1" ErrorHandler : handles >
Company "1" -- "1" FileIO : uses >

Admin "1" -- "1" CustomerService : uses >
Admin "1" -- "1" Payment : manages >
Admin "1" -- "1" Statistic : manages >

TicketHandler "1" -- "1" Location : uses >

@enduml